# Generated by Django 3.2.3 on 2021-06-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='password',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Issue',
            field=models.CharField(default='no data', max_length=100),
        ),
    ]
